{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d38bc519-21a3-4095-8dcd-de0858172cf9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# convertisseur.py\n",
    "\"\"\"\n",
    "Module de démonstration : fonction f(x) avec @singledispatch\n",
    "gérant plusieurs types (int, float, str, list, tuple, dict)\n",
    "\"\"\"\n",
    "\n",
    "from functools import singledispatch\n",
    "from array import array\n",
    "\n",
    "# --- Fonction principale avec @singledispatch --- #\n",
    "@singledispatch\n",
    "def f(x) -> dict:\n",
    "    \"\"\"Fonction générique pour tous les types non enregistrés.\"\"\"\n",
    "    return f\"Type non supporté : {type(x).__name__}\"\n",
    "\n",
    "# --- int --- #\n",
    "@f.register\n",
    "def _(x: int) -> dict:\n",
    "    return {\n",
    "        \"binaire\": bin(x),\n",
    "        \"hexadécimal\": hex(x),\n",
    "        \"int\": x,\n",
    "        \"float\": float(x),\n",
    "        \"str\": str(x)\n",
    "    }\n",
    "\n",
    "# --- float --- #\n",
    "@f.register\n",
    "def _(x: float) -> dict:\n",
    "    return {\n",
    "        \"float\": x,\n",
    "        \"int\": int(x),\n",
    "        \"str\": str(x)\n",
    "    }\n",
    "\n",
    "# --- str --- #\n",
    "@f.register\n",
    "def _(x: str) -> dict:\n",
    "    return {\n",
    "        \"str\": x,\n",
    "        \"list\": list(x),\n",
    "        \"tuple\": tuple(x)\n",
    "    }\n",
    "\n",
    "# --- list --- #\n",
    "@f.register\n",
    "def _(x: list) -> dict:\n",
    "    numeric_items = [i for i in x if isinstance(i, (int, float))]\n",
    "    return {\n",
    "        \"list\": x,\n",
    "        \"tuple\": tuple(x),\n",
    "        \"array\": array('i', numeric_items) if numeric_items else None,\n",
    "        \"str\": str(x)\n",
    "    }\n",
    "\n",
    "# --- tuple --- #\n",
    "@f.register\n",
    "def _(x: tuple) -> dict:\n",
    "    numeric_items = [i for i in x if isinstance(i, (int, float))]\n",
    "    return {\n",
    "        \"tuple\": x,\n",
    "        \"list\": list(x),\n",
    "        \"array\": array('i', numeric_items) if numeric_items else None,\n",
    "        \"str\": str(x)\n",
    "    }\n",
    "\n",
    "# --- dict --- #\n",
    "@f.register\n",
    "def _(x: dict) -> dict:\n",
    "    return {\n",
    "        \"dict\": x,\n",
    "        \"list_clés\": list(x.keys()),\n",
    "        \"list_valeurs\": list(x.values()),\n",
    "        \"str\": str(x)\n",
    "    }\n",
    "\n",
    "# --- Test direct --- #\n",
    "if __name__ == \"__main__\":\n",
    "    exemples = [\n",
    "        42,\n",
    "        3.14,\n",
    "        \"abc\",\n",
    "        [1, 2, 3],\n",
    "        (4, 5, 6),\n",
    "        {\"a\": 1, \"b\": 2}\n",
    "    ]\n",
    "\n",
    "    for e in exemples:\n",
    "        print(f\"\\n--- f({e}) ---\")\n",
    "        for k, v in f(e).items():\n",
    "            print(f\"{k:12} -> {v}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9c98baab-3410-445d-9efb-c3826285f70e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
