{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "cfdc4643-6ba2-44d1-aab4-b24352ab98c4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "BINAIRE : 8\n",
      "→ 0b1000\n",
      "\n",
      "HEXADÉCIMAL : 255\n",
      "→ 0xff\n",
      "\n",
      "INT : 42\n",
      "→ 42\n",
      "\n",
      "FLOAT : 3.14\n",
      "→ 3.14\n",
      "\n",
      "STR : 123\n",
      "→ 123\n",
      "\n",
      "LIST : (1, 2, 3)\n",
      "→ [1, 2, 3]\n",
      "\n",
      "TUPLE : [1, 2, 3]\n",
      "→ (1, 2, 3)\n",
      "\n",
      "ARRAY : [4, 5, 6]\n",
      "→ array('i', [4, 5, 6])\n",
      "\n",
      "DICT : [('a', 1), ('b', 2)]\n",
      "→ {'a': 1, 'b': 2}\n"
     ]
    }
   ],
   "source": [
    "# types_demo.py\n",
    "# Démonstration de fonctions Python pour différents types de données\n",
    "\n",
    "from array import array\n",
    "from typing import Any, List, Tuple\n",
    "\n",
    "# --- Fonctions de conversion simples --- #\n",
    "\n",
    "def to_binary(x: int) -> str:\n",
    "    \"\"\"Retourne la représentation binaire de x (préfixée par 0b).\"\"\"\n",
    "    return bin(x)\n",
    "\n",
    "def to_hex(x: int) -> str:\n",
    "    \"\"\"Retourne la représentation hexadécimale de x (préfixée par 0x).\"\"\"\n",
    "    return hex(x)\n",
    "\n",
    "def to_int(x) -> int:\n",
    "    \"\"\"Convertit x en entier.\"\"\"\n",
    "    return int(x)\n",
    "\n",
    "def to_float(x) -> float:\n",
    "    \"\"\"Convertit x en nombre à virgule flottante.\"\"\"\n",
    "    return float(x)\n",
    "\n",
    "def to_str(x) -> str:\n",
    "    \"\"\"Convertit x en chaîne de caractères.\"\"\"\n",
    "    return str(x)\n",
    "\n",
    "def to_list(x) -> list:\n",
    "    \"\"\"Convertit x en liste (si possible).\"\"\"\n",
    "    return list(x)\n",
    "\n",
    "def to_tuple(x) -> tuple:\n",
    "    \"\"\"Convertit x en tuple (si possible).\"\"\"\n",
    "    return tuple(x)\n",
    "\n",
    "def to_array(x) -> array:\n",
    "    \"\"\"Convertit une séquence numérique en tableau du module array.\"\"\"\n",
    "    return array('i', x)\n",
    "\n",
    "def to_dict(x) -> dict:\n",
    "    \"\"\"Convertit une liste de paires ou un dictionnaire existant.\"\"\"\n",
    "    return dict(x)\n",
    "\n",
    "# --- Fonction principale pour tester toutes les conversions --- #\n",
    "\n",
    "def convert_all(x) -> List[Tuple[str, Any]]:\n",
    "    \"\"\"\n",
    "    Retourne une liste contenant toutes les représentations de x\n",
    "    selon les fonctions définies ci-dessus.\n",
    "    \"\"\"\n",
    "    results = []\n",
    "\n",
    "    try:\n",
    "        results.append((\"binaire\", to_binary(int(x))))\n",
    "    except Exception as e:\n",
    "        results.append((\"binaire\", f\"Erreur: {e}\"))\n",
    "\n",
    "    try:\n",
    "        results.append((\"hexadécimal\", to_hex(int(x))))\n",
    "    except Exception as e:\n",
    "        results.append((\"hexadécimal\", f\"Erreur: {e}\"))\n",
    "\n",
    "    try:\n",
    "        results.append((\"int\", to_int(x)))\n",
    "    except Exception as e:\n",
    "        results.append((\"int\", f\"Erreur: {e}\"))\n",
    "\n",
    "    try:\n",
    "        results.append((\"float\", to_float(x)))\n",
    "    except Exception as e:\n",
    "        results.append((\"float\", f\"Erreur: {e}\"))\n",
    "\n",
    "    try:\n",
    "        results.append((\"str\", to_str(x)))\n",
    "    except Exception as e:\n",
    "        results.append((\"str\", f\"Erreur: {e}\"))\n",
    "\n",
    "    try:\n",
    "        results.append((\"list\", to_list(x)))\n",
    "    except Exception as e:\n",
    "        results.append((\"list\", f\"Erreur: {e}\"))\n",
    "\n",
    "    try:\n",
    "        results.append((\"tuple\", to_tuple(x)))\n",
    "    except Exception as e:\n",
    "        results.append((\"tuple\", f\"Erreur: {e}\"))\n",
    "\n",
    "    try:\n",
    "        results.append((\"array\", to_array(x)))\n",
    "    except Exception as e:\n",
    "        results.append((\"array\", f\"Erreur: {e}\"))\n",
    "\n",
    "    try:\n",
    "        results.append((\"dict\", to_dict(x)))\n",
    "    except Exception as e:\n",
    "        results.append((\"dict\", f\"Erreur: {e}\"))\n",
    "\n",
    "    return results\n",
    "\n",
    "\n",
    "# --- Exemple d'utilisation --- #\n",
    "if __name__ == \"__main__\":\n",
    "    # Exemple : convertir une liste\n",
    "    tests = {\n",
    "        \"binaire\": 8,\n",
    "        \"hexadécimal\": 255,\n",
    "        \"int\": \"42\",\n",
    "        \"float\": \"3.14\",\n",
    "        \"str\": 123,\n",
    "        \"list\": (1, 2, 3),\n",
    "        \"tuple\": [1, 2, 3],\n",
    "        \"array\": [4, 5, 6],\n",
    "        \"dict\": [(\"a\", 1), (\"b\", 2)]\n",
    "    }\n",
    "\n",
    "    for t, val in tests.items():\n",
    "        print(f\"\\n{t.upper()} : {val}\")\n",
    "        for name, result in convert_all(val):\n",
    "            if name == t:\n",
    "                print(f\"→ {result}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b0d7aa36-07b4-47f8-ad16-dc6b8325fb37",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
