{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3831a3ce-ec69-4ee4-aaca-3e708755498f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "--- f(42) ---\n",
      "binaire      -> 0b101010\n",
      "hexadécimal  -> 0x2a\n",
      "int          -> 42\n",
      "float        -> 42.0\n",
      "str          -> 42\n",
      "\n",
      "--- f(3.14) ---\n",
      "float        -> 3.14\n",
      "int          -> 3\n",
      "str          -> 3.14\n",
      "\n",
      "--- f(abc) ---\n",
      "str          -> abc\n",
      "list         -> ['a', 'b', 'c']\n",
      "tuple        -> ('a', 'b', 'c')\n",
      "\n",
      "--- f([1, 2, 3]) ---\n",
      "list         -> [1, 2, 3]\n",
      "tuple        -> (1, 2, 3)\n",
      "array        -> array('i', [1, 2, 3])\n",
      "str          -> [1, 2, 3]\n",
      "\n",
      "--- f((4, 5, 6)) ---\n",
      "tuple        -> (4, 5, 6)\n",
      "list         -> [4, 5, 6]\n",
      "array        -> array('i', [4, 5, 6])\n",
      "str          -> (4, 5, 6)\n",
      "\n",
      "--- f({'a': 1, 'b': 2}) ---\n",
      "dict         -> {'a': 1, 'b': 2}\n",
      "list_clés    -> ['a', 'b']\n",
      "list_valeurs -> [1, 2]\n",
      "str          -> {'a': 1, 'b': 2}\n"
     ]
    }
   ],
   "source": [
    "# convertisseur.py\n",
    "\"\"\"\n",
    "Module de démonstration : fonction f(x) avec @singledispatch\n",
    "gérant plusieurs types (int, float, str, list, tuple, dict)\n",
    "\"\"\"\n",
    "\n",
    "from functools import singledispatch\n",
    "from array import array\n",
    "\n",
    "# --- Fonction principale avec @singledispatch --- #\n",
    "@singledispatch\n",
    "def f(x) -> dict:\n",
    "    \"\"\"Fonction générique pour tous les types non enregistrés.\"\"\"\n",
    "    return f\"Type non supporté : {type(x).__name__}\"\n",
    "\n",
    "# --- int --- #\n",
    "@f.register\n",
    "def _(x: int) -> dict:\n",
    "    return {\n",
    "        \"binaire\": bin(x),\n",
    "        \"hexadécimal\": hex(x),\n",
    "        \"int\": x,\n",
    "        \"float\": float(x),\n",
    "        \"str\": str(x)\n",
    "    }\n",
    "\n",
    "# --- float --- #\n",
    "@f.register\n",
    "def _(x: float) -> dict:\n",
    "    return {\n",
    "        \"float\": x,\n",
    "        \"int\": int(x),\n",
    "        \"str\": str(x)\n",
    "    }\n",
    "\n",
    "# --- str --- #\n",
    "@f.register\n",
    "def _(x: str) -> dict:\n",
    "    return {\n",
    "        \"str\": x,\n",
    "        \"list\": list(x),\n",
    "        \"tuple\": tuple(x)\n",
    "    }\n",
    "\n",
    "# --- list --- #\n",
    "@f.register\n",
    "def _(x: list) -> dict:\n",
    "    numeric_items = [i for i in x if isinstance(i, (int, float))]\n",
    "    return {\n",
    "        \"list\": x,\n",
    "        \"tuple\": tuple(x),\n",
    "        \"array\": array('i', numeric_items) if numeric_items else None,\n",
    "        \"str\": str(x)\n",
    "    }\n",
    "\n",
    "# --- tuple --- #\n",
    "@f.register\n",
    "def _(x: tuple) -> dict:\n",
    "    numeric_items = [i for i in x if isinstance(i, (int, float))]\n",
    "    return {\n",
    "        \"tuple\": x,\n",
    "        \"list\": list(x),\n",
    "        \"array\": array('i', numeric_items) if numeric_items else None,\n",
    "        \"str\": str(x)\n",
    "    }\n",
    "\n",
    "# --- dict --- #\n",
    "@f.register\n",
    "def _(x: dict) -> dict:\n",
    "    return {\n",
    "        \"dict\": x,\n",
    "        \"list_clés\": list(x.keys()),\n",
    "        \"list_valeurs\": list(x.values()),\n",
    "        \"str\": str(x)\n",
    "    }\n",
    "\n",
    "# --- Test direct --- #\n",
    "if __name__ == \"__main__\":\n",
    "    exemples = [\n",
    "        42,\n",
    "        3.14,\n",
    "        \"abc\",\n",
    "        [1, 2, 3],\n",
    "        (4, 5, 6),\n",
    "        {\"a\": 1, \"b\": 2}\n",
    "    ]\n",
    "\n",
    "    for e in exemples:\n",
    "        print(f\"\\n--- f({e}) ---\")\n",
    "        for k, v in f(e).items():\n",
    "            print(f\"{k:12} -> {v}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aa35104b-b82f-44e5-8131-9e17535a7f4d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
